# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_app', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='bonus_app.Courses'),
        ),
    ]
